//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUICore.
//     
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     
//     Add //NoRazorForms comment to .cshtml file to prevent the generation of this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUICore.EmptyProject.RazorForms.Pages
{
	public partial class IndexModel
	{
		protected FineUICore.Panel mainPanel;
		protected FineUICore.Panel sidebarRegion;
		protected FineUICore.Panel sideheaderTopPanel;
		protected FineUICore.Panel leftPanel;
		protected FineUICore.Tree treeMenu;
		protected FineUICore.Panel bodyRegion;
		protected FineUICore.Panel topPanel;
		protected FineUICore.Button btnCollapseSidebar;
		protected FineUICore.Button btnThemeSelect;
		protected FineUICore.MenuButton MenuFramePageStyle;
		protected FineUICore.MenuCheckBox MenuFramePageStyleDarkLeft;
		protected FineUICore.MenuCheckBox MenuFramePageStyleDarkTop;
		protected FineUICore.MenuCheckBox MenuFramePageStyleDarkTopLeft;
		protected FineUICore.MenuButton MenuDisplayMode;
		protected FineUICore.MenuCheckBox MenuDisplayModeCompact;
		protected FineUICore.MenuCheckBox MenuDisplayModeSmall;
		protected FineUICore.MenuCheckBox MenuDisplayModeNormal;
		protected FineUICore.MenuCheckBox MenuDisplayModeLargeSpace;
		protected FineUICore.MenuCheckBox MenuDisplayModeLarge;
		protected FineUICore.MenuButton MenuMainTabs;
		protected FineUICore.MenuCheckBox MenuMainTabsMulti;
		protected FineUICore.MenuCheckBox MenuMainTabsSingle;
		protected FineUICore.MenuButton MenuLang;
		protected FineUICore.MenuCheckBox MenuLangZHCN;
		protected FineUICore.MenuCheckBox MenuLangZHTW;
		protected FineUICore.MenuCheckBox MenuLangEN;
		protected FineUICore.MenuCheckBox MenuLangZHUEY;
		protected FineUICore.MenuText menuTextCopyright;
		protected FineUICore.TabStrip mainTabStrip;
		protected FineUICore.Tab tabHomepage;
		protected FineUICore.Window windowThemeRoller;
	}
}
