//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUICore.
//     
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     
//     Add //NoRazorForms comment to .cshtml file to prevent the generation of this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUICore.EmptyProject.RazorForms.Pages
{
	public partial class LoginModel
	{
		protected FineUICore.Window Window1;
		protected FineUICore.SimpleForm SimpleForm1;
		protected FineUICore.TextBox tbxUserName;
		protected FineUICore.TextBox tbxPassword;
		protected FineUICore.Toolbar Toolbar1;
		protected FineUICore.Button btnLogin;
		protected FineUICore.Button btnReset;
	}
}
