//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by FineUICore.
//     
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//     
//     Add //NoRazorForms comment to .cshtml file to prevent the generation of this file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineUICore.EmptyProject.RazorForms.Pages.OPBasic
{
	public partial class OpSettingModel
	{
		protected FineUICore.Panel Panel7;
		protected FineUICore.Form Form5;
		protected FineUICore.TwinTriggerBox ttbSearch;
		protected FineUICore.DropDownList dllApproval;
		protected FineUICore.Grid OPGrid;
		protected FineUICore.Toolbar Toolbar2;
		protected FineUICore.Button btnPopupWindow;
		protected FineUICore.ToolbarSeparator ToolbarSeparator1;
		protected FineUICore.Button btnCheckSelection;
		protected FineUICore.ToolbarSeparator ToolbarSeparator2;
		protected FineUICore.Button btnDelete;
		protected FineUICore.ToolbarSeparator ToolbarSeparator3;
		protected FineUICore.Button btnCopy;
		protected FineUICore.Button btnApproval;
		protected FineUICore.Window Window1;
	}
}
